font:
    svg:        font/comicsyns.svg
    ttf:        font/comicsyns.ttf
    eot:        font/comicsyns.eot
    woff:       font/comicsyns.woff
    css:        font/comicsyns.css
    html:       font/comicsyns.html
    name:       ComicSyns
    prefix:     ComicSyns
    fixedwidth: false
    height:     1000
    descent:    350
    normalize:  true
    center:     true
    round:      10e12
glyphs:
    - glyph:    glyphs-stroketopath/line.svg
      name:     line
      code:     0x005F
    - glyph:    glyphs-stroketopath/promoter.svg
      name:     promoter
      code:     0x0070
    - glyph:    glyphs-stroketopath/rbs.svg
      name:     rbs
      code:     0x0072
    - glyph:    glyphs-stroketopath/cds.svg
      name:     cds
      code:     0x0063
    - glyph:    glyphs-stroketopath/terminator.svg
      name:     terminator
      code:     0x0074
    - glyph:    glyphs-stroketopath/promoter_left.svg
      name:     promoter-left
      code:     0x0050
    - glyph:    glyphs-stroketopath/cds_left.svg
      name:     cds-left
      code:     0x0043
    - glyph:    glyphs-stroketopath/ori.svg
      name:     ori
      code:     0x006F
      

